# Generated by Django 5.0.3 on 2024-03-30 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='algorithm',
            fields=[
                ('Alg_ID', models.AutoField(primary_key=True, serialize=False)),
                ('alg_name', models.TextField()),
                ('title', models.TextField()),
                ('number_of_parameters', models.IntegerField()),
                ('parameters_name', models.TextField()),
                ('capacity_formula', models.TextField(blank=True, null=True)),
                ('capacity_formula_latex', models.TextField(blank=True, null=True)),
                ('tree_structure', models.ImageField(upload_to='images/')),
                ('pseudocode', models.TextField(blank=True, null=True)),
                ('algorithm_code', models.TextField(blank=True, null=True)),
                ('href_code', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='interpretation',
            fields=[
                ('Interp_ID', models.AutoField(primary_key=True, serialize=False)),
                ('n_value', models.TextField()),
                ('description', models.TextField()),
                ('example_text', models.TextField(blank=True, null=True)),
                ('example_image', models.ImageField(upload_to='images/')),
                ('example_table', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sequence_desc',
            fields=[
                ('M_ID', models.AutoField(primary_key=True, serialize=False)),
                ('OEIS_ID', models.CharField(max_length=255, unique=True)),
                ('special_title', models.TextField()),
                ('number_of_parameters', models.IntegerField()),
                ('recurrent_formula', models.TextField(blank=True, null=True)),
                ('explicit_formula', models.TextField(blank=True, null=True)),
                ('other_formula', models.TextField(blank=True, null=True)),
                ('explicit_formula_latex', models.TextField(blank=True, null=True)),
                ('other_formula_latex', models.TextField(blank=True, null=True)),
                ('recurrent_formula_latex', models.TextField(blank=True, null=True)),
                ('generating_function', models.TextField(blank=True, null=True)),
                ('generating_function_latex', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sequence_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Alg_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdapp.algorithm')),
                ('Interp_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdapp.interpretation')),
                ('M_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdapp.sequence_desc')),
            ],
        ),
    ]
