# Generated by Django 5.1.7 on 2025-03-10 14:53

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='algorithm',
            fields=[
                ('Alg_ID', models.AutoField(primary_key=True, serialize=False)),
                ('alg_name', models.TextField()),
                ('alg_type', models.CharField(choices=[('Listing', 'Listing'), ('Rank', 'Rank'), ('Unrank', 'Unrank')], default='Listing', max_length=10)),
                ('parameters_name', models.TextField(default='N')),
                ('number_of_parameters', models.IntegerField()),
                ('field_name', models.TextField(blank=True, default='')),
                ('field_description', django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Описание')),
                ('alg_code', models.TextField()),
                ('update_date_algorithm', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='interpretation',
            fields=[
                ('Interp_ID', models.AutoField(primary_key=True, serialize=False)),
                ('interpretation_name', models.TextField()),
                ('interpretation_description', django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Описание')),
                ('update_date_interpretation', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='sequence_desc',
            fields=[
                ('M_ID', models.AutoField(primary_key=True, serialize=False)),
                ('OEIS_ID', models.CharField(max_length=255, unique=True)),
                ('sequence_name', models.TextField(default='', verbose_name='Числовая последовательность')),
                ('sequence_description', django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Описание')),
                ('update_date_sequence_desc', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='sequence_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date_sequence_tb', models.DateTimeField(auto_now=True)),
                ('Alg_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdapp.algorithm')),
                ('Interp_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdapp.interpretation')),
                ('M_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdapp.sequence_desc')),
            ],
        ),
    ]
