# Generated by Django 5.0.3 on 2024-05-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algorithm',
            old_name='title',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='algorithm',
            old_name='capacity_formula',
            new_name='field1_text',
        ),
        migrations.RenameField(
            model_name='algorithm',
            old_name='capacity_formula_latex',
            new_name='field2_text',
        ),
        migrations.AddField(
            model_name='algorithm',
            name='alg_table_title',
            field=models.CharField(default='Описание алгоритма, Формула мощности, Структура дерева И/ИЛИ, Псевдокод алгоритма, Источник иформации'),
        ),
    ]
