# Generated by Django 5.0.3 on 2024-11-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdapp', '0002_rename_title_algorithm_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algorithm',
            old_name='description',
            new_name='alg_code',
        ),
        migrations.RemoveField(
            model_name='algorithm',
            name='alg_table_title',
        ),
        migrations.RemoveField(
            model_name='algorithm',
            name='algorithm_code',
        ),
        migrations.RemoveField(
            model_name='algorithm',
            name='field1_text',
        ),
        migrations.RemoveField(
            model_name='algorithm',
            name='field2_text',
        ),
        migrations.RemoveField(
            model_name='algorithm',
            name='href_code',
        ),
        migrations.RemoveField(
            model_name='algorithm',
            name='parameters_name',
        ),
        migrations.RemoveField(
            model_name='algorithm',
            name='pseudocode',
        ),
        migrations.AddField(
            model_name='algorithm',
            name='field1_desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='field1_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='field2_desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='field2_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='field3_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='field4_desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='field4_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='field5_desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='field5_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='tree_structure',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='interpretation',
            name='example_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
