# Generated by Django 5.0.3 on 2024-11-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdapp', '0003_rename_description_algorithm_alg_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='parameters_name',
            field=models.TextField(default='N'),
        ),
    ]
