# Generated by Django 5.0.3 on 2025-01-04 10:28

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdapp', '0007_remove_interpretation_example_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequence_desc',
            name='explicit_formula_latex',
        ),
        migrations.RemoveField(
            model_name='sequence_desc',
            name='generating_function_latex',
        ),
        migrations.RemoveField(
            model_name='sequence_desc',
            name='other_formula_latex',
        ),
        migrations.RemoveField(
            model_name='sequence_desc',
            name='recurrent_formula',
        ),
        migrations.RemoveField(
            model_name='sequence_desc',
            name='recurrent_formula_latex',
        ),
        migrations.AddField(
            model_name='interpretation',
            name='example_text',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', max_length=500, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='sequence_desc',
            name='desc',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', max_length=500, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='interpretation',
            name='description',
            field=models.TextField(),
        ),
    ]
