# Generated by Django 5.0.3 on 2025-01-04 13:30

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdapp', '0008_remove_sequence_desc_explicit_formula_latex_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interpretation',
            old_name='description',
            new_name='interpretation_name',
        ),
        migrations.RemoveField(
            model_name='algorithm',
            name='field1_desc',
        ),
        migrations.RemoveField(
            model_name='algorithm',
            name='field1_name',
        ),
        migrations.RemoveField(
            model_name='algorithm',
            name='field2_desc',
        ),
        migrations.RemoveField(
            model_name='algorithm',
            name='field2_name',
        ),
        migrations.RemoveField(
            model_name='algorithm',
            name='field3_name',
        ),
        migrations.RemoveField(
            model_name='algorithm',
            name='field4_desc',
        ),
        migrations.RemoveField(
            model_name='algorithm',
            name='field4_name',
        ),
        migrations.RemoveField(
            model_name='algorithm',
            name='field5_desc',
        ),
        migrations.RemoveField(
            model_name='algorithm',
            name='field5_name',
        ),
        migrations.RemoveField(
            model_name='algorithm',
            name='tree_structure',
        ),
        migrations.RemoveField(
            model_name='interpretation',
            name='example_text',
        ),
        migrations.RemoveField(
            model_name='interpretation',
            name='n_value',
        ),
        migrations.RemoveField(
            model_name='sequence_desc',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='sequence_desc',
            name='number_of_parameters',
        ),
        migrations.RemoveField(
            model_name='sequence_desc',
            name='special_title',
        ),
        migrations.AddField(
            model_name='algorithm',
            name='field_description',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='field_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='interpretation',
            name='interpretation_description',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='sequence_desc',
            name='sequence_description',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Описание'),
        ),
    ]
