# Generated by Django 5.0.3 on 2025-01-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdapp', '0009_rename_description_interpretation_interpretation_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='update_date_algorithm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='interpretation',
            name='update_date_interpretation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sequence_desc',
            name='update_date_sequence_desc',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sequence_tb',
            name='update_date_sequence_tb',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
