# Generated by Django 5.0.3 on 2025-01-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdapp', '0010_algorithm_update_date_algorithm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequence_desc',
            name='update_date_sequence_desc',
        ),
    ]
