# Generated by Django 5.0.3 on 2025-01-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdapp', '0011_remove_sequence_desc_update_date_sequence_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence_desc',
            name='update_date_sequence_desc',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
